# -*- coding: utf-8 -*-
"""Orientation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-IKplP9X1ellPFzqoYe4H77h41bGb4p

Example of Addition
"""

A=2
B=3
C=2+3
print(C)

"""Example of a String"""

Greetings= "Advice na, pror"
print(Greetings)