# -*- coding: utf-8 -*-
"""Python_refresher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Ckgp1tMc_ox9JGmJgAq7pvJMnTpCQI6

Variables
"""

# crate a labeled storage basket and put a number inside
tomato_price = 150
pepper_price = 80

# Pull the value out of the basket
print(tomato_price)
print(pepper_price)

"""Variables (ML Anchor)"""

#--- THE CLUES (Features grouped as X) ---
rainfall_mm = 45.2   # Clue 1
bags_available = 100 # Clue 2

# --- THE GOAL (Target labeled as y) ---
predicted_price = 3200  # What our AI calculates

print("Inputs (X):", rainfall_mm, "mm rain,", bags_available, "bags.")
print("Output (y):", predicted_price, "LRD.")

"""Understanding Print statements"""

Liberia= 1847
print(Liberia)
print("Liberia")

"""Understanding Variables"""

plum=50
print("plum previous price was:",plum)
plum=80
print("plum new price is:",plum)

"""DATA TYPES"""

quantity = 50
price = 150.50
item_name = "tomatoes"
stall_is_open = True

print(type(quantity)) #
print(type(price)) #
print(type(item_name)) #
print(type(stall_is_open)) #